import {
   Build,
   DesktopMac,
   DirectionsWalk,
   FileOpen,
   ArrowLeft,
   Visibility,
   Menu,
   Close,
   Link,
   LinkedIn,
   Person3,
   ExpandLess,
   ExpandMore,
   AttachMoney,
   Public,
   BarChart,
   Create,
   Logout,
   LoginOutlined,
   HowToReg,
   DeleteOutline,
} from "@mui/icons-material";

export const icons = {
   MuiCompanyIcon: DesktopMac,
   MuiJobIcon: DirectionsWalk,
   MuiProfileIcon: Build,
   MuiReseumeIcon: FileOpen,
   MuiBackIcon: ArrowLeft,
   MuiEyeIcon: Visibility,
   MuiMenuIcon: Menu,
   MuiCloseIcon: Close,
   MuiLinkIcon: Link,
   MuiLinkedinIcon: LinkedIn,
   MuiEmployeeIcon: Person3,
   MuiExpandLess: ExpandLess,
   MuiExpandMore: ExpandMore,
   MuiAttachMoneyIcon: AttachMoney,
   MuiGlobeIcon: Public,
   MuiChartIcon: BarChart,
   MuiPenIcon: Create,
   MuiLogoutIcon: Logout,
   MuiLoginIcon: LoginOutlined,
   MuiSignupIcon: HowToReg,
   MuiDeleteIcon: DeleteOutline,
};
