export const COMPANY_DETAIL_SUBJECT = "COMPANY_DETAIL_SUBJECT";
export const JOB_DETAIL_SUBJECT = "JOB_DETAIL_SUBJECT";
export const CREATE_NEW_RESUME_SUBJECT = "CREATE_NEW_RESUME_SUBJECT";
export const ADD_NEW_SECTION_TO_RESUME_SUBJECT = "ADD_NEW_SECTION_TO_RESUME_SUBJECT";
